name: Integration test
on: [push, pull_request]
env:
  SPOT-VERSION: 2.11.5
jobs:
  test-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Building spot takes time, so we cache it.
      - name: Cache Spot
        id: cache-spot
        uses: actions/cache@v3
        env:
          cache-name: cache-spot
        with:
          path: spot-${{SPOT-VERSION}}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ SPOT-VERSION }}
      - if: ${{ steps.cache-spot.outputs.cache-hit != 'true' }}
        name: Build Spot
        run: |
          ## Download the source code of spot
          wget http://www.lrde.epita.fr/dload/spot/spot-${{ SPOT-VERSION }}.tar.gz
          tar xvf spot-${{ SPOT-VERSION }}.tar.gz
          cd spot-${{ SPOT-VERSION }}
          # Specify appropriate CPU/OS for your environment
          ./configure --prefix "$OLDPWD/.venv/" --build=x86_64-unknown-linux-gnu --host=x86_64-unknown-linux-gnu
          # Build Spot
          make -j8

      - name: Set-up Python venv
        run: python3 -m venv .venv
      - name: Install spot
        run: |
          cd spot-${{ SPOT-VERSION }}
          make install
      - name: Install AALpy
        run: |
          git clone https://github.com/DES-Lab/AALpy -b v.1.4.1 --depth 1
          . .venv/bin/activate
          cd AALpy
          patch -p1 < ../aalpy.patch
          python3 -m pip install pydot
          sudo python3 setup.py install
      - name: Install other packages
        run: |
          . .venv/bin/activate
          pip install -r requirements.txt
      - name: Run src/main.py as an integration test
        run: |
          . .venv/bin/activate
          python3 src/main.py \
            --model-file benchmarks/mqtt/mqtt.dot \
            --prop-file benchmarks/mqtt/mqtt.props \
            --prism-path foo/bin/prism \
            --output-dir result \
            --min-rounds 3 \
            --max-rounds 5 \
            --save-files-for-each-round \
            --target-unambiguity 0.99
